from asyncio import subprocess
import json
import os
from Agents.Logger import logger
from Agents.Agent import Agent
from Agents.Tools.Tools import extract_json, to_b64
from Agents.Tools.FileClassifier import get_file_classifier
from Agents.Tools.LLM import llm_run



class DoxygenConfigBuilder(Agent):
    """
    Enhanced Doxygen configuration builder with actual Doxygen CLI generation.

    Workflow:
    1. Generates deterministic Doxyfile base using 'doxygen -g'.
    2. Generates base header.html, footer.html, stylesheet.css via Doxygen.
    3. Uses LLM to analyze project (languages, protocols, tools, versions, licenses, Markdown docs)
       and optimize Doxyfile & assets.
    """

    def __init__(self):
        super().__init__(
            "DoxygenConfigBuilder",
            depends_on=[
                "ProjectTreeAnalyzer",
                "LanguageDetector",
                "BuildSystemDetector",
                "DependencyDetector",
                "CodeArchitectureAnalyzer",
                "APIAnalyzer",
                "UsageAnalyzer",
                "DocumentationAnalyzer",
                "MDDocumentationMaker"
            ]
        )

    def generate_doxygen_base(self, project_root: str) -> dict:
        """
        Generate deterministic base Doxyfile, header/footer/css using Doxygen CLI.
        Returns paths and asset content.
        """
        base_dir = os.path.join(project_root, "_doxygen_base")
        os.makedirs(base_dir, exist_ok=True)

        doxyfile_path = os.path.join(base_dir, "Doxyfile")

        # Step 1: Generate Doxyfile base
        subprocess.run(["doxygen", "-g", doxyfile_path], check=True)

        # Step 2: Optionally, generate HTML assets (header/footer/css) via Doxygen
        # Create a minimal config to output HTML assets
        subprocess.run(["doxygen", doxyfile_path], check=True)

        # Read header/footer/css if they exist
        assets = {}
        for name in ["header.html", "footer.html", "stylesheet.css"]:
            path = os.path.join(base_dir, name)
            if os.path.exists(path):
                with open(path, "r", encoding="utf-8") as f:
                    assets[name] = f.read()
            else:
                assets[name] = ""

        return {"doxyfile_path": doxyfile_path, "assets": assets}

    def run(self, task: dict, crew_context: dict):
        logger.info(f"[{self.name}] start running") 
        cached_result = self.load_existing_result()
        if cached_result:
            self.save_result(crew_context, cached_result)
            return cached_result
        project_root = task.get("project_root", ".")
        base = self.generate_doxygen_base(project_root)

        with open(base["doxyfile_path"], "r", encoding="utf-8") as f:
            base_doxy = f.read()
        assets = base["assets"]

        files_b64 = to_b64(task.get("files_dict", {}))
        context_json = json.dumps(crew_context, indent=2)

        # ----------------------------
        # LLM OPTIMIZATION
        # ----------------------------
        prompt = f"""
        You are an expert in Doxygen configuration, documentation systems, web UI,
        and technical documentation best practices.

        INPUTS:
        - Base Doxyfile generated by 'doxygen -g':
        {base_doxy}

        - Base HTML assets:
        HEADER: {assets.get("header.html","")}
        FOOTER: {assets.get("footer.html","")}
        CSS: {assets.get("stylesheet.css","")}

        - Project files (Base64): {files_b64}

        - Full project context (languages, frameworks, build system, dependencies,
          protocols, tools, versions, licenses, Markdown docs):
        {context_json}

        TASK:
        Optimize Doxyfile parameters based on project structure, Markdown docs,
        APIs, usage patterns, protocols, tools, licenses, versions.

        Ensure:
        - Markdown integration
        - Call graphs, inheritance diagrams, dependency graphs
        - Correct input paths
        - Output formats consistent with project needs

        RETURN JSON:
        {{
            "Doxyfile": "...",
            "header.html": "...",
            "footer.html": "...",
            "stylesheet.css": "...",
            "config_summary": {{
                "parameters": {{ ... }},
                "main_page": "index.html",
                "has_diagrams": true,
                "optimized_for": "GitHub Pages"
            }}
        }}

        Return ONLY valid JSON.
        """

        result = llm_run(prompt, max_tokens=7000)
        parsed = extract_json(result) or {"error": "invalid_json", "raw": result}

        self.save_to_json(data=parsed, raw_content=result)

        # ----------------------------
        # SAVE FILES
        # ----------------------------
        output_dir = os.path.join(project_root, "doxygen_custom")
        os.makedirs(output_dir, exist_ok=True)

        for key in ["Doxyfile", "header.html", "footer.html", "stylesheet.css"]:
            if key in parsed:
                with open(os.path.join(output_dir, key), "w", encoding="utf-8") as f:
                    f.write(parsed[key])

        
        logger.info(f"[{self.name}] result: {parsed}")
        logger.info(f"[{self.name}] end running")
        return parsed

